version: 2

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: daily
      timezone: Europe/London
    target-branch: master
    open-pull-requests-limit: 10

updates:
  - package-ecosystem: github-actions
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: all-dependencies
    cooldown:
      default-days: 7

  - package-ecosystem: uv
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: all-dependencies
    cooldown:
      default-days: 7
    allow:
      - dependency-type: direct
      - dependency-type: indirect
